[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring"]

[phases.install]
cmds = ["mkdir -p /app"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
